package net.jest.reflect;

import lombok.NonNull;
import lombok.experimental.UtilityClass;
import net.jest.api.*;
import net.jest.api.response.Response;
import net.jest.api.util.ResponseUtil;
import net.jest.implementation.request.RealRequestSource;
import net.jest.util.CacheUtil;

import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Function;
import java.util.stream.Collectors;

import static net.jest.util.DebugUtil.print;

@UtilityClass
public class MethodParser {

    // TODO: rewrite it
    public String getName(@NonNull Controller controller, @NonNull java.lang.reflect.Method method) {
        Method annotation = method.getDeclaredAnnotation(Method.class);

        if (annotation == null) return null;

        String path = controller.path() + annotation.name();

        return path;
    }

    public Function<RealRequestSource, Response> parse(@NonNull Controller controller, @NonNull Object instance, @NonNull java.lang.reflect.Method method) {
        String path = getName(controller, method);

        if (path == null) return null;

        List<String> wannableParameters = new ArrayList<>();
        RepeatableParameterAnnotation annotation = method.getDeclaredAnnotation(RepeatableParameterAnnotation.class);

        if (annotation != null) wannableParameters.addAll(Arrays.stream(annotation.value()).map(param -> param.value()).collect(Collectors.toList()));

        Authorization auth = method.getDeclaredAnnotation(Authorization.class);

        if (method.getParameterCount() > 1) {
            throw new IllegalArgumentException("Bad method! Please read documentation!");
        }

        boolean empty = method.getParameterCount() == 0;

        // i need rewrite it
        return request -> {

            if (auth != null
                    && CacheUtil.putIfAbsent(auth.value()) != null
                    && !CacheUtil.putIfAbsent(auth.value()).isAuthorized(request.getExchange(), request)) {
                return ResponseUtil.createResponse(ResponseUtil.UNAUTHORIZED, "Cant authorize your request. Please read api documentation. (The message is generated by the Jest framework)");
            }

            if (wannableParameters.size() > request.getParameters().size()) return ResponseUtil.createResponse(ResponseUtil.BAD_REQUEST, "You have not specified enough parameters. Read the documentation. (The message is generated by the Jest framework)");

            AtomicReference<Response> response = new AtomicReference<>(null);

            wannableParameters.forEach((name) -> {
                try {
                    if (!request.containsParameter(name)) response.set(ResponseUtil.createResponse(ResponseUtil.BAD_REQUEST, "The " + name + " argument was not found. (The message is generated by the Jest framework)"));
                }
                catch (Exception e) {
                    e.printStackTrace();
                    response.set(ResponseUtil.createResponse(ResponseUtil.INTERNAL_SERVER_ERROR, "Internal server error during process request. (The message is generated by the Jest framework)"));
                }
            });

            if (response.get() != null) return response.get();

            try {
                if (method.getReturnType().isAssignableFrom(Response.class) || method.getReturnType().equals(Response.class)) return (Response) (empty ? method.invoke(instance) : method.invoke(instance, request));
                return ResponseUtil.createResponse(ResponseUtil.OK, empty ? method.invoke(instance) : method.invoke(instance, request));
            }
            catch (Exception e) {
                e.printStackTrace();
                return ResponseUtil.createResponse(ResponseUtil.INTERNAL_SERVER_ERROR, "Internal server error during method invoke. (The message is generated by the Jest framework)");
            }
        };
    }
}
